services:
  db:
    image: postgres
    container_name: geohub_database
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '5432:5432'
    volumes:
      - geohub_data:/var/lib/postgresql

volumes:
  geohub_data:
